// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvkdbsgkttnvfubexbpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2a2Ric2drdHRudmZ1YmV4YnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDMyNzYsImV4cCI6MjA2ODc3OTI3Nn0.MwTqddXmiO_ExL9p8EdwQe06dEPswne0f3R9cXZmW_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});